name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'

  setup:
    runs-on: [ubuntu-latest]
    
    steps:
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 10.x
        # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN
        # registry-url: # optional
        # Optional scope for authenticating against scoped registries
        # scope: # optional
